CC := gcc
CFLAGS := -Wall -Wextra -O2 -I../include

TESTS := test_phase1_driver test_phase2_dma test_phase3_dmabuf test_phase4_rdma test_phase5_numa test_phase6_backpressure test_phase7_instrumentation

all: $(TESTS)

test_phase1_driver: test_phase1_driver.c
	$(CC) $(CFLAGS) -o $@ $< -lpthread

test_phase2_dma: test_phase2_dma.c
	$(CC) $(CFLAGS) -o $@ $<

test_phase3_dmabuf: test_phase3_dmabuf.c
	$(CC) $(CFLAGS) -o $@ $<

test_phase4_rdma: test_phase4_rdma.c
	$(CC) $(CFLAGS) -o $@ $<

test_phase5_numa: test_phase5_numa.c
	$(CC) $(CFLAGS) -o $@ $<

test_phase6_backpressure: test_phase6_backpressure.c
	$(CC) $(CFLAGS) -o $@ $<

test_phase7_instrumentation: test_phase7_instrumentation.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	rm -f $(TESTS)
